### ISSUE TITLE
Plugin Development

### ISSUE THREAD

**Issue by landwire** [tyxla/gravity-forms-section-tabs#1]
Hi there,

will you continue to work on this plugin? It's exactly what I was thinking of doing, but it makes sense to wrap it all into a flexible plugin.

**Comment by tyxla** [comment]
Hey there @landwire ,

Yes, this is one of the next plugins that i'll work on. Now that someone is interested, I'll definitely have it done soon. 

Stay tuned! :)

**Comment by tyxla** [comment]
The plugin is now ready for use, in case you need it. 

I still have to compose a readme and write some documentation before uploading it to wordpress.org plugin repository, but overall that's all that remains to be done.

Please, don't hesitate to ask any questions, and I'd love to receive ideas for new features or enhancement, or any other feedback.

**Comment by landwire** [comment]
Hello Marin,
thanks soo much. I will try it in the next weeks and happily give you some feedback!
Sascha
