### ISSUE TITLE
Missing argument 3 for

### ISSUE THREAD

**Issue by riazsha** [tyxla/gravity-forms-section-tabs#15]
Missing argument 3 for GFSectionTabsAddon::gform_pre_render() 

i am using gravity form and have this error

**Comment by tyxla** [comment]
Thanks for reporting! I'll investigate and fix the issue later today.

**Comment by tyxla** [comment]
Hey @riazsha,

Feel free to pull the latest version. The issue has been fixed.

Thank you for reporting! I wish you good luck with your project.

Regards,
Marin
