### ISSUE TITLE
Problem with install

### ISSUE THREAD

**Issue by vainucleo** [tyxla/gravity-forms-section-tabs#17]
Hi,

I don't seem to be able to use ur great plugin: after installation (and activation on a multisite WP environment) it doesn't even appear on GF settings :(

I really need this :) pls any advice?

Thanks!!!

**Comment by tyxla** [comment]
Hi @vainucleo ,

Thanks for reporting the issue. The addon was not compatible with Multisite, but now it is.

Feel free to use the latest plugin files to get the multisite-compatible version.

Thanks,
Marin
