### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by gillespieza** [tyxla/gravity-forms-section-tabs#20]
I've installed this plugin and activated it, but there are no instructions on how to use it. I have a basic form, with some sections, but nothing has changed on the front end, and I don't see any new options on the back end?

**Comment by tyxla** [comment]
Howdy @gillespieza!

Yeah, I never got to finalize and release this plugin. But I'd love to help you get it working. 

So, you install the plugin, and then you create a form, and in the form settings of each form you'll see the "Section Tabs" section. There, if you enable the "Enable Section Tabs" checkbox, it will convert all sections to tabs. So basically, you insert section fields, and fields below them. The plugin will turn each section into a tab, containing all fields below it until the next section.

Feel free to try it out, and let me know if you have any other questions.
